(cl:defpackage maze-msg
  (:use )
  (:export
   "<M_GOAL>"
   "M_GOAL"
   "<MAZESOLVERACTION>"
   "MAZESOLVERACTION"
   "<MAZESOLVERACTIONFEEDBACK>"
   "MAZESOLVERACTIONFEEDBACK"
   "<MAZESOLVERACTIONGOAL>"
   "MAZESOLVERACTIONGOAL"
   "<MAZESOLVERACTIONRESULT>"
   "MAZESOLVERACTIONRESULT"
   "<MAZESOLVERFEEDBACK>"
   "MAZESOLVERFEEDBACK"
   "<MAZESOLVERGOAL>"
   "MAZESOLVERGOAL"
   "<MAZESOLVERRESULT>"
   "MAZESOLVERRESULT"
  ))

