; Auto-generated. Do not edit!


(cl:in-package maze-msg)


;//! \htmlinclude mazeSolverResult.msg.html

(cl:defclass <mazeSolverResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:string
    :initform ""))
)

(cl:defclass mazeSolverResult (<mazeSolverResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mazeSolverResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mazeSolverResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name maze-msg:<mazeSolverResult> is deprecated: use maze-msg:mazeSolverResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <mazeSolverResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader maze-msg:success-val is deprecated.  Use maze-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mazeSolverResult>) ostream)
  "Serializes a message object of type '<mazeSolverResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'success))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'success))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mazeSolverResult>) istream)
  "Deserializes a message object of type '<mazeSolverResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'success) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'success) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mazeSolverResult>)))
  "Returns string type for a message object of type '<mazeSolverResult>"
  "maze/mazeSolverResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mazeSolverResult)))
  "Returns string type for a message object of type 'mazeSolverResult"
  "maze/mazeSolverResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mazeSolverResult>)))
  "Returns md5sum for a message object of type '<mazeSolverResult>"
  "6563811f75f3715f19a981f2cc0a3560")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mazeSolverResult)))
  "Returns md5sum for a message object of type 'mazeSolverResult"
  "6563811f75f3715f19a981f2cc0a3560")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mazeSolverResult>)))
  "Returns full string definition for message of type '<mazeSolverResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mazeSolverResult)))
  "Returns full string definition for message of type 'mazeSolverResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mazeSolverResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'success))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mazeSolverResult>))
  "Converts a ROS message object to a list"
  (cl:list 'mazeSolverResult
    (cl:cons ':success (success msg))
))
