// Generated by gencpp from file maze/det_srv.msg
// DO NOT EDIT!


#ifndef MAZE_MESSAGE_DET_SRV_H
#define MAZE_MESSAGE_DET_SRV_H

#include <ros/service_traits.h>


#include <maze/det_srvRequest.h>
#include <maze/det_srvResponse.h>


namespace maze
{

struct det_srv
{

typedef det_srvRequest Request;
typedef det_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct det_srv
} // namespace maze


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maze::det_srv > {
  static const char* value()
  {
    return "ee92c41b1aa6150e49f8725366020017";
  }

  static const char* value(const ::maze::det_srv&) { return value(); }
};

template<>
struct DataType< ::maze::det_srv > {
  static const char* value()
  {
    return "maze/det_srv";
  }

  static const char* value(const ::maze::det_srv&) { return value(); }
};


// service_traits::MD5Sum< ::maze::det_srvRequest> should match 
// service_traits::MD5Sum< ::maze::det_srv > 
template<>
struct MD5Sum< ::maze::det_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maze::det_srv >::value();
  }
  static const char* value(const ::maze::det_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maze::det_srvRequest> should match 
// service_traits::DataType< ::maze::det_srv > 
template<>
struct DataType< ::maze::det_srvRequest>
{
  static const char* value()
  {
    return DataType< ::maze::det_srv >::value();
  }
  static const char* value(const ::maze::det_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maze::det_srvResponse> should match 
// service_traits::MD5Sum< ::maze::det_srv > 
template<>
struct MD5Sum< ::maze::det_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maze::det_srv >::value();
  }
  static const char* value(const ::maze::det_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maze::det_srvResponse> should match 
// service_traits::DataType< ::maze::det_srv > 
template<>
struct DataType< ::maze::det_srvResponse>
{
  static const char* value()
  {
    return DataType< ::maze::det_srv >::value();
  }
  static const char* value(const ::maze::det_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAZE_MESSAGE_DET_SRV_H
