// Generated by gencpp from file maze/det_srvResponse.msg
// DO NOT EDIT!


#ifndef MAZE_MESSAGE_DET_SRVRESPONSE_H
#define MAZE_MESSAGE_DET_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maze
{
template <class ContainerAllocator>
struct det_srvResponse_
{
  typedef det_srvResponse_<ContainerAllocator> Type;

  det_srvResponse_()
    : success(false)
    , goal(0)  {
    }
  det_srvResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , goal(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::maze::det_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maze::det_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct det_srvResponse_

typedef ::maze::det_srvResponse_<std::allocator<void> > det_srvResponse;

typedef boost::shared_ptr< ::maze::det_srvResponse > det_srvResponsePtr;
typedef boost::shared_ptr< ::maze::det_srvResponse const> det_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maze::det_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maze::det_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace maze

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'maze': ['/home/rakesh/flytbase/mazesolver/src/maze/msg', '/home/rakesh/flytbase/mazesolver/devel/.private/maze/share/maze/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::maze::det_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maze::det_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maze::det_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maze::det_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maze::det_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maze::det_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maze::det_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4d98e39076ae8da08ac539ca4323ba";
  }

  static const char* value(const ::maze::det_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4d98e39076ae8dULL;
  static const uint64_t static_value2 = 0xa08ac539ca4323baULL;
};

template<class ContainerAllocator>
struct DataType< ::maze::det_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maze/det_srvResponse";
  }

  static const char* value(const ::maze::det_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maze::det_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
int32 goal\n\
";
  }

  static const char* value(const ::maze::det_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maze::det_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct det_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maze::det_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maze::det_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAZE_MESSAGE_DET_SRVRESPONSE_H
